### ISSUE TITLE
How to enable apache modules?

### ISSUE THREAD

**Issue by digedag** [nimmis/docker-alpine-apache#2]
What is the preferred way to enable other modules in apache config?
I use `nimmis/alpine-apache-php5` and need to enable mod_rewrite.

**Comment by digedag** [comment]
To answer this question myself. I was wrong to try to change config in `/web/config/httpd.conf`. This will not work as this file isn't available during build and even not when run_once scripts are executed.
To enable `mod_rewrite` the following line in my Dockerfile worked:
```
RUN sed -i 's@^#LoadModule rewrite_module modules/mod_rewrite\.so@LoadModule rewrite_module modules/mod_rewrite.so@' /etc/apache2/httpd.conf
```
Maybe this will help someone.

**Comment by tuncerdamat** [comment]
@digedag  Actually this made the trick in my case, thank you! :)
